# Generated by Django 5.1.15 on 2026-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_create_tag'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tags.tag', verbose_name='Теги'),
        ),
    ]
