# Generated by Django 5.1.15 on 2026-02-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_tags_m2m'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_position_non_negative',
        ),
    ]
