# Generated by Django 5.1.15 on 2026-01-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Цвет')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'name'], name='tags_tag_project_ce67ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_tag_name_per_project')],
            },
        ),
    ]
