# Generated by Django 5.1.15 on 2026-01-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_create_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6B7280', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате HEX (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет'),
        ),
    ]
